AnimationStateMachine.copyState2 ExpPack v_arg1
AnimationStateMachine.copyState2 MedPack v_arg1
AnimationStateMachine.copyState2 Detonator v_arg1
AnimationStateMachine.copyState2 Landmine v_arg1
AnimationStateMachine.copyState2 RepairPack v_arg1
AnimationStateMachine.copyState2 Colt v_arg1
AnimationStateMachine.copyState2 No4 v_arg1
AnimationStateMachine.copyState2 GrenadeAxis v_arg1
AnimationStateMachine.copyState2 GrenadeAllies v_arg1
AnimationStateMachine.copyState2 Binoculars v_arg1
AnimationStateMachine.copyState2 KnifeAllies v_arg1
AnimationStateMachine.copyState2 KnifeAxis v_arg1
AnimationStateMachine.copyState2 Bazooka v_arg1
AnimationStateMachine.copyState2 M1Garand v_arg1
AnimationStateMachine.copyState2 Type5 v_arg1

rem ** special for reusing 3P animations from other weapons.

AnimationStateMachine.copyState K98 v_arg1 No4 1.0 K98 1.0
AnimationStateMachine.copyState K98Sniper v_arg1 No4 1.0 K98 1.0
AnimationStateMachine.copyState No4Sniper v_arg1 No4 1.0 No4 1.0
AnimationStateMachine.copyState Panzershreck v_arg1 Bazooka 1.0 Panzershreck 1.0
AnimationStateMachine.copyState WalterP38 v_arg1 Colt 1.0 WalterP38 1.0

rem *** Mod weapons
include singleShotWeaponsMod.inc v_arg1









